events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Todo lo que empiece con /api se envía al Backend
        location /api/ {
            # Se conecta internamente al contenedor 'backend' en su puerto 4000
            proxy_pass http://backend:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Todo lo que sea imágenes (uploads) también va al Backend
        location /uploads/ {
            proxy_pass http://backend:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Todo lo demás (las vistas del e-commerce) se envía al Frontend
        location / {
            # Se conecta internamente al contenedor 'frontend' en su puerto 3000
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Esto es vital para que funcionen las rutas de React/Vue (si usas router)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}